version: "3.8"
services:
  paymentapi:
    build:
      context: .
      dockerfile: PaymentAPI/Dockerfile
    image: paymentapi:1.0
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped